### ISSUE TITLE
Version output in command line 

### ISSUE THREAD

**Issue by ilmanzo** [ArgonLang/Argon#29]
according to 
```
❯ ./Argon --help
usage: ./Argon [option] [-c cmd | file] [arg] ...

Options and arguments:
-c cmd         : program string
-h, --help     : print this help message and exit
-i             : start interactive mode after running script
--nogc         : disable garbage collector
-q             : don't print version messages on interactive startup
-u             : force the stdout stream to be unbuffered
-v, --version  : print Argon version and exit
```

the `-v` option should output the version number, but doesn't output anything.

running `./Argon` without any option I get the version number and an unexpected interactive prompt.

**Comment by jacopodl** [comment]
Initiating an interactive prompt when no file is provided as an argument is the intended behavior, even though it's not explicitly mentioned in the program's help.

However, the incorrect behavior of the `-v` switch has been fixed.

Thank you!
